.TH XKBDBIND 1 xkbdbind
.SH NAME
xkbdbind - global hotkeys for X
.SH SYNOPSIS
.B xkbdbind
.SH DESCRIPTION
.B xkbdbind
lets the user configure keybindings to start programs.
.PP
xkbdbind is a configured by the user by editing the
.I config.h
source file and recompiling the program. The user shall
therefore have a local copy of the software, and a personal
installation of it.
